add_subdirectory(utils)
add_subdirectory(config)
add_subdirectory(logger)
add_subdirectory(net)
add_subdirectory(mcp)
add_subdirectory(db)

target_include_directories(csj_utils PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(csj_config PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(csj_log PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(csj_net PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(csj_mcp PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(csj_db PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})